version: '3.4'

services:
  alexbot:
    build: .
    # command: python bot.py
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://alexbot:alexbot@db/alexbot
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: alexbot
      POSTGRES_PASSWORD: alexbot
      POSTGRES_DB: alexbot
    volumes:
      - alex-bot-db:/var/lib/postgresql/data
volumes:
  alex-bot-db:
