version: '3.4'

services:
  alexbot:
    build: .
    # command: python bot.py
    restart: unless-stopped
    depends_on:
      - db
    environment:

    env_file:
      - .env
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: alexbot
      POSTGRES_PASSWORD: alexbot
      POSTGRES_DB: alexbot
    volumes:
      - alex-bot-db:/var/lib/postgresql/data
volumes:
  alex-bot-db:
